#!/usr/bin/env bash
# A Bash script that transfers a file from client to a server
if [ $# -lt 4 ]; then
  exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~
