#!/usr/bin/env bash
# Install nginx
apt-get -y update
apt-get -y install nginx
# Create the content for the default Nginx page
echo "Hello World!" > /var/www/html/index.html
# Configure Nginx to listen on port 80
sed -i '/listen 80 default_server;/a listen 80;' /etc/nginx/sites-available/default
# Reload Nginx configuration
service nginx reload
