#!/usr/bin/env bash
# configures a new Ubuntu machine
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/ permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
sudo service nginx restart
