#!/usr/bin/env bash
# Install Nginx if not installed
if ! dpkg -l | grep -q "nginx"; then
    apt-get -y update
    apt-get -y install nginx
fi

echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect_me
ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
service nginx restart

