#!/usr/bin/env bash
# Install Nginx if not installed
if ! dpkg -l | grep -q "nginx"; then
    apt-get -y update
    apt-get -y install nginx
fi

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "server {
    listen 80;
    server_name _;
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/404_custom_page
ln -sf /etc/nginx/sites-available/404_custom_page /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
service nginx restart
