#!/usr/bin/env bash
# Change IP for localhost and facebook.
if grep -q "127.0.0.1" /etc/hosts; then
    sudo sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts
else
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
fi
echo "8.8.8.8 facebook.com" >> /etc/hosts
