#!/usr/bin/env bash
# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Update localhost entry to 127.0.0.2
sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts

# Add an entry for facebook.com pointing to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts

# sudo cp /etc/hosts.bak /etc/hosts
# sudo systemctl restart networking.service

